### ISSUE TITLE
Support for Tasmota32

### ISSUE THREAD

**Issue by s-hadinger** [tube0013/tube_gateways#1]
Hi, great devices.

I'm interested in adding this device to the Tasmota compatibility list. It should be straightforward, and would make a great coordinator device working in standalone.

I have ordered an EFR32 based device, but would be interested in the CC too.

https://tasmota.github.io/docs/Zigbee/

Edit: I forgot to mention I'm the coder of the Zigbee features in Tasmota

**Comment by tube0013** [comment]
Thanks @s-hadinger

**Comment by Hedda** [comment]
@tube0013 Congrats on Tube's Zigbee Gateways cc2652p2 variant now being officially supported by Tasmota for ESP32!

s-hadinger wrote "**_The Tube's cc2652p2 is now officially supported. The EFR32 will be shortly._**" in https://github.com/arendst/Tasmota/issues/9081

**Comment by Hedda** [comment]
@s-hadinger Is there a "zbbridge" specific version of Tasmota32 that should be used on ESP32 based Zigbee bridges/gateways?

**Comment by Hedda** [comment]
FYI, posted a question about Zigbee2Tasmota (Z2T) compatibility/support for the CC2652P varient here -> https://github.com/arendst/Tasmota/discussions/12457
