### ISSUE TITLE
LEDs on CC2652P2 PoE

### ISSUE THREAD

**Issue by gdgib** [tube0013/tube_gateways#122]
Any way to disable, dim, or control the LEDs on this module (https://tubeszb.com/products/cc2652p2-based-zigbee-to-poe-coordinator-2022) through software?    Just checking if there's a recommended way before I mask them with electrical tape or just de-solder them.

It's a fantastic coordinator, of course.  Thanks so much for selling them.

It's just that in a smarthome full of devices, I don't need more LEDs on all the time.

**Comment by tube0013** [comment]
unfortunately no, the LEDs on the Olimex ESP32-PoE are controlled by hardware only.

**Comment by gdgib** [comment]
I figured.  Thanks!
