### ISSUE TITLE
Update TubesZB CC2652 PoE Coordiniator OTA Network Upgrade Procedure

### ISSUE THREAD

**Issue by mrosun** [tube0013/tube_gateways#140]
The upgrade procedures [here](https://github.com/tube0013/tube_gateways/tree/main/models/current/tubeszb-cc2652-poe-2022) over the network, are not up to date.

My coordinator's GUI looks different than what is on the instructions page and I'm not sure which toggle(s) to activate prior to OTA update.

![Screenshot from 2023-03-12 12-55-54](https://user-images.githubusercontent.com/319488/224563214-beaa66d3-7940-40ab-b29e-7a44b349f60e.png)

For example, I don't know which is the toggle "Trigger Zigbee Module Bootloader" or if something has changed.

Also, if we're updating through the web interface, how do we run "Run the cc2538-bsl flasher" command, since there's no text input on the interface?

**Comment by tube0013** [comment]
In the Web Interface OTA Update Section is for ESPHome/ESP32 firmware.

For CC2652 - you toggle the Prep the cc2652p2 for firmware update

then on computer in a terminal/command prompt (not the web site) you run the cc-2538-bsl.py script to update the 
firmware. 

Recommend grabbing latest ESPHome firmware from model's fw directory and flashing the new esp32 firmware before doing the cc2652.

**Comment by mrosun** [comment]
Ahhh, now I understand, thank you!

**Comment by tube0013** [comment]
the screen shots are from newer ESPHome build, the language changed a bit to try to make clearer. sorry for the confusion.

**Comment by mrosun** [comment]
I just updated the ESPHome firmware and can see the new interface.

**Comment by mrosun** [comment]
When I try to update the cc2652 I get the following error:

`Opening port socket://192.168.47.11:6638, baud 500000
Reading data from CC1352P2_CC2652P_launchpad_coordinator_20221226.hex
Firmware file: Intel Hex
Connecting to target...
ERROR: No response from target on status request. (Did you disable the bootloader?)
`

I did follow the instructions to Trigger Zigbee Module Bootloader, as can be seen below:

![Screenshot from 2023-03-12 13-47-05](https://user-images.githubusercontent.com/319488/224565843-24f9aa3c-64f5-4dcd-a8ac-06bc2437a29c.png)

Do you have any further advice?

**Comment by mrosun** [comment]
Ahh the failed attempts looks like it broke the communication to Home Assistant:

`Zigbee2MQTT:error 2023-03-12 13:53:04: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)`

**Comment by tube0013** [comment]
only one thing can access the coordinator at a time, so shut down z2m when doing the update.

https://github.com/tube0013/tube_gateways/blob/main/Troubleshooting.md#zigbee2mqtt-startup---error-srsp---sys---ping-after-6000ms

**Comment by mrosun** [comment]
That was the issue! I can't believe I didn't think of that =(

Thanks for everything.
