### ISSUE TITLE
Firmware update doesn't work for tube-zb-gw-cc2652p2-v2

### ISSUE THREAD

**Issue by Cafun** [tube0013/tube_gateways#144]
Hi!

I'd like some help with flashing my tube-zb-gw-cc2652p2-v2 coördinator.
When I run the command bellow, it just returns to the prompt.
![image](https://user-images.githubusercontent.com/25382117/230573320-b86324ee-e631-430a-ab45-fef0da4a7b3b.png)

Here is the debug log on the tube:
![image](https://user-images.githubusercontent.com/25382117/230573673-75e951ee-858a-4e84-9796-fc20e1510fde.png)

I don't know what I'm doing wrong.
Hope you can help. Thanks.

Regards,
Cafun

**Comment by verstrepeng** [comment]
Hi,
I think it's because you're missing
`-evw`
in the command line.
KR,
Geert

**Comment by Cafun** [comment]
Right! Thanks. It worked.

The [documentation](https://github.com/tube0013/tube_gateways/tree/main/models/current/tubeszb-cc2652-eth_usb#network) doesn't states the -evw in the command line. I tried it, but got an error the IntelHex library could not be imported. It also isn't in the documentation, so I thought I would not need those options and the IntelHex library.

**Comment by tube0013** [comment]
thank for calling out the issues in the docs, I've updated to include the -evw switch that was missing and also link to the cc2538-bsl's docs on dependencies.

**Comment by Cafun** [comment]
Thanks for updaten the docs. Maybe it was obvious for most, but not for me ;-)
