### ISSUE TITLE
BOM and and Gerber files for new Tube USB CC2652P2 USB Coordinator

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#15]
BOM and Gerber files for new Tube USB CC2652P2 USB Coordinator ("Version 1") if it too is also open source hardware licensed(?).

https://github.com/tube0013/tube_gateways/tree/main/tube_usb_cc_coordinator

Bin image file for the firmware is also missing. but guess really only need to include link to https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin

PS: @tube0013 you might also want to consider submit PR updating this README.md file:

https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin

Update: Submitted this PR based on the info available so far -> https://github.com/Koenkk/Z-Stack-firmware/pull/287

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md

PPS: Off-topic but related; it would also be interesting to know if Tube USB CC2652P2 USB Coordinator support this router firmware:

https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin

**Comment by tube0013** [comment]
think most of this is done/out of date so closing.
