### ISSUE TITLE
Ckicking ESPHome or the firmware link does nothing

### ISSUE THREAD

**Issue by LordNex** [tube0013/tube_gateways#159]
Through iOS GitGub app or through safari

**Comment by tube0013** [comment]
From which page is the bad link? 

Thanks

**Comment by LordNex** [comment]
Bottom of

<https://github.com/tube0013/tube_gateways>
tube0013/tube_gateways: Information and Documentation on Tube's Zigbee Gateways<https://github.com/tube0013/tube_gateways>
github.com<https://github.com/tube0013/tube_gateways>
[apple-touch-icon-180x180.png]<https://github.com/tube0013/tube_gateways>


Benjamin T Powers

On Oct 11, 2023, at 5:30 PM, tube0013 ***@***.***> wrote:

﻿

From which page is the bad link?

Thanks

**Comment by tube0013** [comment]
It's linking to itself due to its Markup Level. its meant to be a comment as to where to find the firmware, not a link to a particular one.
