### ISSUE TITLE
Older Tubeszb-CC2652p2-poe-v2: Serial pin out

### ISSUE THREAD

**Issue by samip5** [tube0013/tube_gateways#177]
There's the middle connector on the board, but what's the pin-out of it?

I don't own an USB serial adapter.. but I do have RPis..

I would need to troubleshoot why it won't show up in network or appear to do much of anything.

(It's one of the round ones)

**Comment by tube0013** [comment]
See schematic here: https://github.com/tube0013/tube_gateways/blob/main/models/retired/tubeszb-cc2652-poe/gerber_files/Schematic_Zigbee-eth32-2652P2%20POE%20No%20ISO.pdf

**Comment by samip5** [comment]
What's the baud rate when connected though the USB and is that only for connecting to zigbee2mqtt via USB or can I debug though it?

**Comment by tube0013** [comment]
115200 and those pins are going only to the zigbee module. The olimex esp32 can be debugged from the microUSB on the side of the module. Just don't use PoE Ethernet when connected to usb as you will likely kill you computer's usb or the module or both.

**Comment by samip5** [comment]
> The olimex esp32 can be debugged from the microUSB on the side of the module.

That's the USB I'm talking about, aka MicroUSB next to the RJ45 connector, I tried 115200 but got either gibberish or nothing.

**Comment by tube0013** [comment]
That's 115200 too.

If you don't get anything I'd suspect the esp32-Poe is dead.

**Comment by samip5** [comment]
Does `��` characters count when doing `screen /dev/ttyUSB0 115200`?

**Comment by tube0013** [comment]
Yeah you should get the ESPHome logs. 

Send me an email at store@tubeszb.com and I'll see if we can work something out.

**Comment by samip5** [comment]
Alright, sent you an email.
