### ISSUE TITLE
Z-Wave PoE Kit unresponsive

### ISSUE THREAD

**Issue by jpnwalters** [tube0013/tube_gateways#185]
![IMG_0179](https://github.com/tube0013/tube_gateways/assets/1087677/67b588f2-e566-480f-8fda-5999929eea46)

I recently purchased the Z-Wave PoE kit and I can't seem to pull down an IP address. I've attached a picture showing the LEDs that are lit. I've confirmed the port is a PoE port, it works, and so does the cable. If I power the device over USB and instead plug into a non-PoE port, I see the same LEDs lit and no address is pulled down. I'm happy to help troubleshoot if you have some thoughts.

**Comment by tube0013** [comment]
Hi, Sorry for the trouble.

I've seen this a few times now, and have swapped one recently and when I got it back it worked fine for me, so I am not fully sure why this happens.

What type of PoE Switch and Router are you using from your network?

Have/Can you try a different ethernet cable.

You can also try re-flashing the firmware over microUSB, https://github.com/tube0013/tube_gateways/tree/main/models/current/tubeszb-zw-kit

If you want to try a static ip build to see if that makes a difference the Yaml is at the same link, and can be brought into esphome, modified and complied, or I can compile if you provide the ip/gateway and subnet.

**Comment by jpnwalters** [comment]
I went ahead and reflashed with your web flasher binary and it booted right up. For what it's worth, it was connected to a Ubiquiti US-8-60W.

**Comment by tube0013** [comment]
Good to hear. Interesting, same switch I'm using for testing, and my network.
