### ISSUE TITLE
ESPHome 2024.03 update issue

### ISSUE THREAD

**Issue by davidrule1969** [tube0013/tube_gateways#187]
In ESPHome 2024.03, the function **network::get_ip_address()** has been renamed to **network::get_ip_addresses()**

https://esphome.io/changelog/2024.3.0.html

![Screenshot 2024-03-20 at 10 15 35 am](https://github.com/tube0013/tube_gateways/assets/33907199/0f916290-f87d-4e5b-aebb-c9d3694046fe)

**Comment by stormy64** [comment]
Looks like this is fixed now in https://github.com/tube0013/esphome-stream-server-v2
Thank you

**Comment by davidrule1969** [comment]
Perfect, thanks!
