### ISSUE TITLE
Import oxan's serial stream server custom component for ESPHome as an external component in ESPHome

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#19]
FYI, @oxan has now made his UART/Serial stream server available as a new external component for ESPHome v1.18+ on GitHub:

https://github.com/oxan/esphome-stream-server

```
external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
```

ESPHome version 1.18 and later has added a new feature to support such external component which can now easily be imported:

https://esphome.io/components/external_components.html

**Comment by tube0013** [comment]
done with most recent updates (v2 still pending but will come).
