### ISSUE TITLE
EFR32 MGM24 unavailable after firmware upgrade

### ISSUE THREAD

**Issue by hanzoh** [tube0013/tube_gateways#200]
After successfully upgrading the firmware to 8.0.1.0 via your HA addon (the progress log showed 100% and then disconnected gracefully), I can no longer connect to the adapter.
The ESP32 side is fine (I even reflashed it via USB with your factory ESPhome binary) and I can see also see that Z2M starts a serial connection, but it is directly disconnected again.

I have then removed the MGM24 board from the ESP32-PoE board and connected 3.3V, GND, RX, TX, CTS, RTS to an FT232 USB adapter.
With that, I also cannot make any connection with any tool (SiLabs commander, ember-zli).

Do you have any idea how I could restore the MGM24 chip?

**Comment by tube0013** [comment]
I will try to build a new addon release today with the latest univeral-silicon-labs flasher from nabu-casa which should allow downgrading from 8.0.x. 8.0.x had major changes.

Another option is to hold the boot button on the device or putting it boot loader mode via the ESPHome web dashboard this will launch the gecko bootloader and allow flashing. You could then use the standalone universal-silabs-flasher to flash. (It should also work without the button 285) the latest release)
