### ISSUE TITLE
Z-Wave PoE Kit -ZooZ

### ISSUE THREAD

**Issue by MrMxyzptlk** [tube0013/tube_gateways#214]
I just installed this in Home Assistant and it's working great.

I just rebooted HA, and now it's also auto discovering this?

<img width="317" alt="Screenshot 2024-12-25 at 1 38 25 PM" src="https://github.com/user-attachments/assets/e4f1285c-2e4d-4b0a-83f3-e86a7ce14d0f" />

Do I need to configure or disable something to stop this from being discovered, or is this also a ZHA device?
If so, how do I add it...it fails when I try?

Thank you.

**Comment by tube0013** [comment]
Please ignore it, it's an artifact of the discovery process for zha and should be fixed in a ha release in the future.

**Comment by MrMxyzptlk** [comment]
Thanks
