### ISSUE TITLE
[Device Configuration] Setting Static IP - EFR32 Pro

### ISSUE THREAD

**Issue by ardysusilo** [tube0013/tube_gateways#24]
**Enhancement**
Provide guideline on how to set a static IP address on EFR32 Pro Coordinator.

**Reason**
To perform a restoration of my previous Sonoff ZBBridge configuration without repairing router and child devices.

**Comment by tube0013** [comment]
to use a static ip you'd need to compile a custom build of the esphome fw for the esp32.

What I'd recommend is assigning/locking the address with your router.

You can then update your core.config_entities in the .storage folder in HA and update the IP address for the ZHA entry.

you will need to back up your ZBBridge and Restore it to the new coordinator with bellows to migrate without repairing devices. <https://github.com/zigpy/zigpy/wiki/Coordinator-Backup-and-Migration>

**Comment by tube0013** [comment]
.storage/core.config_entities: make sure you back it up as any errors will cause HA to fail to start. You'd just need to change the path (and optionally the title) to match the address given to the new coordinator.

![image](https://user-images.githubusercontent.com/11084412/122075018-ba236580-cdc7-11eb-9d53-3295135b2b7d.png)

**Comment by ardysusilo** [comment]
Thank you. Sorry I did not read that you already explain about setting a static IP [here](https://github.com/tube0013/tube_gateways/blob/main/esphome/README.md).

I will try to set a static IP first via ESP Home add-on. If it fails, I will use DHCP reservation to make sure the IP never change.

Looking forward for the coordinator to arrive :)

**Comment by tube0013** [comment]
haha, I forgot I added that <https://github.com/tube0013/tube_gateways/tree/main/esphome>

I'll double check it's up-to-date too as things are traveling.
