### ISSUE TITLE
Add support for "Improv" open standard for setting Wi-Fi via Bluetooth (using a smart phone) in tube gateways firmware

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#26]
Home Assisistant announced ESPHome support for "Improv" open standard to configure network via Bluetooth using a smartphone.

Maybe you would consider adding support for "Improv via Bluetooth" to tube gateways firmware for setting a static IP address?

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/#improv-wi-fi-open-standard-to-provision-wi-fi-credentials-via-bluetooth-low-energy

https://www.improv-wifi.com

Home Assisistant also announced ESP Web Tools for simplifying onboarding by enabling website flashing ESP firmware via webserial:

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/#esp-web-tools-installing-projects-on-your-microcontroller-via-the-browser

https://esphome.github.io/esp-web-tools/

https://esphome.github.io/esp-web-tools/#add-website

Home Assisistant have posted nice videos as part of the announcement  which demos both "ESP Web Tools" and "Improv" features:

https://www.youtube.com/watch?v=du38Oir_xp8

https://www.youtube.com/watch?v=k88BS8zgWq0&t=1s&ab_channel=NabuCasa

https://www.youtube.com/watch?v=AdCsX7Ni6Jc

By the way, they mention at the end of the O&A section of that video that they also plan to add support for "Improv via serial" in the future so that can configure WiFi network and/or IP-address via webserial directly after flashing firmware via "ESP Web Tools".

PS: They also announced ESPHome Dashboard has been updated with a simplified and streamlined wizard for new configurations:

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/#esphome-dashboard-simplified-and-streamlined

https://www.youtube.com/watch?v=luE1hjCf3HI

PPS: This was part of a larger article about making ESP firmware projects more user-friendly and easier to get started and work with: 

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/

**Comment by tube0013** [comment]
No intention to ever use WiFi with my devices, users are free to experiment but I won't support it.
