### ISSUE TITLE
Energy scan issue

### ISSUE THREAD

**Issue by mmychu** [tube0013/tube_gateways#36]
I'm trying to debug why I can't start using Tube's CC2652p2, but with no success
I can't start the device, tried with unscrewed antenna but with no success. Have this issue  https://github.com/Koenkk/zigbee2mqtt/issues/8282 

Later, wanted to debug Energy scan but with no success too
![image](https://user-images.githubusercontent.com/25245131/136712233-4e9fd6e5-4b60-44d0-bebd-afc6cb185dda.png)

**Comment by tube0013** [comment]
Which version coordinator do you have?

If network base are you able to access the esphome web ui via a web browser and going to the ip?

**Comment by mmychu** [comment]
Yes, I'm using HasOS VM (on Proxmox). I'm back to conbee2 with z2m and will try again tomorrow
