### ISSUE TITLE
Suggest design next-gen Tube's Zigbee Gateway as modular with seperate Zigbee Radio Shield compatible with the Raspberry Pi GPIO Header

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#38]
Would like to suggest redesigning your next Tube Gateway to have a pin-header compatible with the standard Raspberry Pi GPIO.

Similar to what fairecasoimeme did with this ZiGate-Ethernet platform which is primarily designed to be used with his PiZiGate:

https://github.com/fairecasoimeme/ZiGate-Ethernet

https://zigate.fr/documentation/descriptif-de-la-zigate-ethernet/

https://zigate.fr/produit/zigate-ethernet/

https://zigate.fr/produit/pizigatev2/

As a bonus users could then buy Tube's Zigbee Shield separately and use it on the Raspberry Pi GPIO header without the gateway.

"**_The GPIOs are compatible with the Raspberry Pi GPIOs. Here is the correspondence of the GPIO with the ESP32_**":

![image](https://user-images.githubusercontent.com/6320001/138668746-4bbc170b-b277-4718-9db8-f91f46625e52.png)

Because of this design ZiGate-Ethernet gateway can not only be used with PiZiGate but also with other Zigbee shields for RPI.

Including technically supporting adapter shields from other manufacturers such as PiZiGate, RaspBee I/II, and Elelabs EFR32 shield:

https://zig-star.com/projects/zigbee-shield/

https://github.com/egony/cc2652p_cc1352p_RF-STAR/wiki/Home-EN#shield-for-single-board-computers

https://github.com/egony/cc2652p_E72-2G4M20S1E/wiki/Home-EN#shield-pi-hat-for-single-board-computers

https://zigate.fr/produit/pizigatev2/

https://phoscon.de/en/raspbee2

https://phoscon.de/en/raspbee

https://elelabs.com/products/elelabs-zigbee-shield.html

https://www.popp.eu/zb-shield/

And while not tested it should in theory also work with Aeotec and z-wave.me Z-Wave adapters and other radio adapters as well 

https://aeotec.com/z-wave-home-automation/development-kit-pcb.html

https://z-wave.me/products/razberry/

Meaning that the ZiGate-Ethernet platform could really be used as a serial stream server proxy for any serial shield for RPI.

![image](https://user-images.githubusercontent.com/6320001/138668934-4058c4ed-8c30-4a09-8a3e-6a8d3c265da2.png)

![image](https://user-images.githubusercontent.com/6320001/138668958-fd030c22-6d0f-43d2-8911-40eb2a8f12ef.png)

![image](https://user-images.githubusercontent.com/6320001/138668991-1ff9997f-68c7-4435-bd13-36a6cdb17c08.png)

![image](https://user-images.githubusercontent.com/6320001/138669002-b654088d-b0cb-4c93-a780-79722911690a.png)

**Comment by tube0013** [comment]
not really interested in making a pi shield.
