### ISSUE TITLE
tasmota method

### ISSUE THREAD

**Issue by Tao173** [tube0013/tube_gateways#42]
Is it possible to use Tasmota's Serial to TCP Bridge option to connect to zigbee2mqtt instead of Z2T? This is its related introduction.[https://tasmota.github.io/docs/Serial-to-TCP-Bridge/](url)

**Comment by tube0013** [comment]
Yes, you could use tasmota as the serial bridge instead of esphome. I am not sure of the setting to do this but it should be easy to figure out based on the esphome yaml files on GitHub which show the pins.

**Comment by Tao173** [comment]
That's great! I will try.
