### ISSUE TITLE
Test and verify Koenkk experimental firmware for CC2652P configurable up to 20 dBm TX power output

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#47]
FYI, Koenkk has now uploaded an experimental firmware for CC2652P/CC1352P with a default set to 9 dBm (and a max of 20 dBm):

https://github.com/Koenkk/Z-Stack-firmware/issues/323

He mentions in https://github.com/Koenkk/zigbee2mqtt/issues/8885 that he does not have RF measurement equipment so cannot confirm RF output power.

Would be great if you can test and verify Koenkk experimental firmware for CC2652P configurable up to 20 dBm TX power output.

**Comment by tube0013** [comment]
users are free to experiment. Sticking with the stable branch for now.
