### ISSUE TITLE
Integrating Switchbot MQTT to ESPHome running in gw

### ISSUE THREAD

**Issue by samip5** [tube0013/tube_gateways#49]
Hi,

I just got my gw, I'm wondering if the ESP Home could be expanded on it to do more, like to run https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32 as well via ethernet?

**Comment by tube0013** [comment]
Bluetooth uses 2.4ghz as well as WiFi/zigbee so I don't advise using it at the same time as zigbee as it may cause interference.

For sure you can experiment!

**Comment by samip5** [comment]
I take it that the "main brains" of the POE gw is an ESP32 (which version/brand/name in Platformio?) that's running ESPHome and the Zigbee module is the CC2652.

**Comment by tube0013** [comment]
PoE device used the Olimex ESP32-PoE - current version has an ESP32-WROOM-32E on it.
