### ISSUE TITLE
Updated ESPHome on my tube-zb-gw-cc2652p2-v2 and now it doesn't work :)

### ISSUE THREAD

**Issue by hvddrift** [tube0013/tube_gateways#55]
I did exactly the same as:

> So I think I messed up my coordinator, but not really sure how. It is the tube-zb-gw-cc2652p2-v2 model :)
> 
> I updated ESPHome to the tube-zb-gw-cc2652p2-v2_2022_01_15.bin that was posted on GitHub, that worked fine, but then I could not connect to the serial port on 6638. I rolled it back to tube-zb-gw-cc2652p2-v2_2021_09_17.bin which was what I wasn on previously, but it still did not work. I attempted to flash new zstack code onto it, but that just fails - I was able to update it to this version of zstack a few days ago without problems.

But I am unable to get the device into boot mode.

I have the jumpers in this postion

![image](https://user-images.githubusercontent.com/972926/153199237-5f8fe5cc-480e-4d94-b3da-76e0d68a9f10.png)

I hold down boot, plug in the device, but my windows PC does not see it.

Any suggestions?

**Comment by tube0013** [comment]
Windows needs the ch340 serial driver. Does device show in device manager?

**Comment by hvddrift** [comment]
No, but I did add the driver

**Comment by hvddrift** [comment]
Just want to make sure I am doing it correctly. 

Photo of jumpers and boot button I am pressing.

I hold the boot down, plug into the USB and release. I get no sound of a USB device being plugged in like other devices.

![image](https://user-images.githubusercontent.com/972926/153212154-b845cc77-51c3-4d9a-8c20-5ae6c5e8b2db.png)

**Comment by tube0013** [comment]
that's all good, but you don't have the ESP32 module on the board so there is nothing to put into boot mode or talk to over serial.

**Comment by hvddrift** [comment]
Ok. Old age mistake there. I could not read the PCB so I was took off what I thought was just the ethernet connector,

Let's see if I can get it to work.

P.S I feel both embarrassed and stuip

**Comment by tube0013** [comment]
no worries. and not discounting something could be wrong.  

Also I saw yo post on twitter, and there is no compatible PoE module with this device. The PoE model I sell is has a different esp32 which has a different pin out, and is much larger. If you want poe I'd advise getting a PoE > micro usb + ethernet splitter.

**Comment by hvddrift** [comment]
Ok... Still no luck. I have an adapter
![PXL_20220209_140028465](https://user-images.githubusercontent.com/972926/153216353-72a00022-f39a-41b2-89a4-6accedb3b3e0.jpg)

I could try to connect with tx,rx, gnd and 3.3

**Comment by tube0013** [comment]
yes, you can give that a try. is the board getting power over usb? (lights on the esp32 light up at all?)

**Comment by hvddrift** [comment]
Just plugged into a USB power board to check. No lights there either.

**Comment by tube0013** [comment]
nothing n the esp32? there will be no lit leds on the tubeszb pcb, but should see some on the esp32 when powered up.

It is possible the usb connector has come loose. and this could be causing the issues - no power or serial.

can you try to power the esp32 module separately with the adaptor you showed? 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/11084412/153218783-310cc8de-8550-4ccf-83fd-ed355832e260.png">

**Comment by hvddrift** [comment]
![PXL_20220209_141943671](https://user-images.githubusercontent.com/972926/153219832-3883fe44-b18e-43f8-9b07-7570fc32fca5.jpg)

Ok, we can power the esp32 module

**Comment by hvddrift** [comment]
And a close up of the USB connector
![PXL_20220209_142119572](https://user-images.githubusercontent.com/972926/153220195-9a0bdf07-28c1-497d-955a-1c520d8dd227.jpg)

**Comment by tube0013** [comment]
okay thanks. 

that's a better picture than I could have gotten ;) 

do you have a multimeter by chance?

**Comment by hvddrift** [comment]
yes

**Comment by tube0013** [comment]
could try and update the FW on the router, new build I put out ups the tx strengh a little bit.

**Comment by hvddrift** [comment]
And that's using this method correct?

https://github.com/tube0013/tube_gateways#zigbee-module-firmware-updates

**Comment by hvddrift** [comment]
And that's using this method, right?

https://github.com/tube0013/tube_gateways#zigbee-module-firmware-updates

But with a serial adapter. Is there a page with instructions for this?

**Comment by tube0013** [comment]
I actually just add the router specific flashing guide here:

https://github.com/tube0013/tube_gateways/tree/main/tube_cc_router#flashing-the-router

**Comment by hvddrift** [comment]
Where you able to test if the 3.3 v is ok for the short term?

**Comment by tube0013** [comment]
no still in my office. can check in a few hours.. I have to build some devices as well before I can confirm as I don't have any on hand.

**Comment by tube0013** [comment]
confirmed 3.3v from a usb serial adapter powers the board up including the esp32 when using the 3.3v and GND pins on the PCB.

**Comment by hvddrift** [comment]
Ok, will test now. 

However, I wanted to update the routers first (as I wont have my serial adapter) and I have tested with both a Linux and Windows machine and I get this error on the flash attempt.

```
Opening port COM3, baud 500000
Reading data from tubeszb_router_20220111.hex
Your firmware looks like an Intel Hex file
ERROR: Hex file contains invalid record at line 7
```

**Comment by tube0013** [comment]
my bad, I should have zipped the .hex file. I just replaced it with a zipped version,  pull this down and unzip and use it to flash I think that will solve this.

https://github.com/tube0013/tube_gateways/raw/main/tube_cc_router/firmware/tubeszb_router_20220111.hex.zip

**Comment by hvddrift** [comment]
Getting closer.... 

```
Opening port COM3, baud 500000
Reading data from tubeszb_router_20220111.hex.zip
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:23:7D:FC:D5
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 193671 bytes starting at address 0x00000000
ERROR: Invalid data size: 193671. Size must be a multiple of 4.
```

**Comment by hvddrift** [comment]
Nope, had to unzip.... Flashing now

**Comment by tube0013** [comment]
looks good. you'll need this essentially factory resets them as well, so you'll need to rejoin them once coordinator is back up.

**Comment by hvddrift** [comment]
And I think I will need to solder a header on the board first. This is where I connect the 3.3 and GND to correct?

![chrome_V7UFlF4aTH](https://user-images.githubusercontent.com/972926/153319474-0d8cb372-c61d-48b3-a5bb-8207971a72ee.png)

**Comment by tube0013** [comment]
correct.

**Comment by hvddrift** [comment]
OK... All seems to be up. I was not able to keep my devices, But I thought I might as well start of right. 

From a tweet I posted. Would you change the channel?
![FLJYODuakAAJ7xK](https://user-images.githubusercontent.com/972926/153335370-3ffe90a5-db31-49c5-b485-e3bddf6414fc.png)
![FLJYofFaIAAKX_-](https://user-images.githubusercontent.com/972926/153335378-a972d67a-667f-4324-8054-923689425908.png)

**Comment by hvddrift** [comment]
And the first device I added wad the freshly flashed router. Its 4 feet way.  But RSSI is Unknown.

Just not sure if this is a symptom of bigger issues. 

![chrome_ZHlfV0VwW4](https://user-images.githubusercontent.com/972926/153337442-9a7ad596-e40e-4cfb-aab9-4681a513c1cc.png)

**Comment by hvddrift** [comment]
Made a big change and switched to zigbee2mqtt.

At this point I could not be happier. I find it so much better and more robust that ZHA.

Just seeing if or how we can rectify the usb tracing issue. Can I get a replacement board?

**Comment by tube0013** [comment]
can you send me an email at my store email - store @ tubeszb.com and we can figure something out.

thansk!
