### ISSUE TITLE
Question - E180-ZG120B programing  

### ISSUE THREAD

**Issue by araczkowski** [tube0013/tube_gateways#6]
Hi @tube0013 

I'm trying to connect to Ebyte E180 via J-Link by Segger to do SWD flashing.

in the ebyte manual I found this:
![image](https://user-images.githubusercontent.com/1263968/113476288-eb53f100-947a-11eb-8512-7b8a95dec6d3.png)

unfortunately I'm not sure how to localize the PF0 and PF1 on the E180-ZG120B-TB board
ebyte|j-link
--------|------
VCC |vref 
?|SWDCLK
?| SWDIO
GND|GND

![image](https://user-images.githubusercontent.com/1263968/113476540-5b16ab80-947c-11eb-8f68-7e7172dc6648.png)

**Could you please give me a hint - how you did this?**
Thanks :+1:

**Comment by tube0013** [comment]
![image](https://user-images.githubusercontent.com/11084412/113481458-b68a6e80-9467-11eb-84e7-6a8deaedaa13.jpeg)

It's the 2 pins I tried to mark in red.

My father's paternal grandparents (I think) - I am told they came to America from Eastern Poland. But I do not know much of the family history on that branch.

**Comment by araczkowski** [comment]
Thanks :+1: 

I already figured out this :)

now I'm testing this, and I described step by step... a note for myself to be able to do this again... 
https://github.com/sviete/AIS-EZSP

![image](https://user-images.githubusercontent.com/1263968/113481896-6a0d5600-949c-11eb-812d-10fff559a5b5.png)


We are working on project AI-Speaker Open Source based on Home Assistant and Zigbee2Mqtt. Your approach with zigbee gate looks very impressive and promising for me. Especially that we are on Android and by default we don't have serial in kernel. + we have some experience with Tasmota and ESP staff.

I thought that maybe you are from Poland and I would like you to join us and sell your devices to our users. But then I figured out that you are from America. Unfortunately the delivery costs, taxes and CE certificate will be to big cost for us and for our users. To give you full picture -> currently we are selling CC2531 devices for about 9$ (with support and 2 year warranty) and some our potential customers still prefer shopping in Aliexpress and waiting 1-2 months ;) So I'm not proposing you to join us and sell your devices, because I now that this will not work, sadly in Poland the market here is still very sensitive to price. 

But I will ask you directly - do you mind if I use your approach to create similar gate for our project?
I'm not sure if this will be our direction, I'm still checking all the possibilities for the more powerful Zigbee for our project.. I already tried with  Wifi zigbee bridge https://ai-speaker.discourse.group/t/zigbee-w-asystencie-domowym-inne-mozliwosci/1545 (sorry our forum is in Polish only) all works fine but wifi if no the best idea, I prefer Ethernet. 
I can join your project if possible, your solution seems to be very promising... for the future we can thing about BLE too.
 
Please let me know if my ask is not hurting you feelings, it is not my intention :peace_symbol: 
Of course you can take whatever you want from our repos https://github.com/sviete if you are interested to have HA on Android (automation platform + multimedia) I can personally guide you step by step to achieve this :)
 and if you let me join I hope I will be able to give some code back to your repo

Greetings from Poland :) 
Your project is awesome
