### ISSUE TITLE
[SUGGESTION] RTC (Real-Time-Clock) and a clock-battery + a buzzer and RGB LED to the PCB board?

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#64]
Maybe consider adding an RTC (Real-Time-Clock) and a clock-battery + a buzzer and tri-color RGB LED or LEDs if it would not add to much cost to Tube's gateways as products. 

That way they could it would not only be a Zigbee Coordinator bridge or Zigbee Router but the ESPHome part could also serve multiple other purposes like for example an alarm-clock or doorbell-chime/buzzer with flashing lights in seperate colors to show/give status alerts for different things. See example these :

https://www.adafruit.com/product/5125

https://www.adafruit.com/product/5126

I read that the new “ITead SONOFF Zigbee Bridge Pro” in addition to having some kind of a "buzzer" so that it can be used as an alarm or a doorbell chime, and this new "Pro" variant also feature an onboard RTC (Real-Time-Clock) to keep time while offline-> https://github.com/arendst/Tasmota/discussions/14419

With both ESP32 and an RTC it would make it very suitable as a Zigbee2Tasmota gateway -> https://tasmota.github.io/docs/Zigbee/

Zigbee2Tasmota on an ESP32 based gateway RTC (Real-Time-Clock) and clock-battery could be used as a stand-alone offline gateway/hub to keep schemas and schedules for "Wake Up Alarm Clock" even when the internet goes down and it reboot, like when there is power blackout.

**Comment by tube0013** [comment]
This is outside the scope of what I want to do / make. Users can add anything they'd like to the other pins of the esp32, however I can not support problems or issues that may occur.
