### ISSUE TITLE
PoE Coordinator 2022 LEDs

### ISSUE THREAD

**Issue by Cossey** [tube0013/tube_gateways#65]
Is it possible to turn off all LEDs for this device? (PWR1, CHRG, LAN_CON1, ACT1LNK1)

This will be placed on the roof in a common area of a residential house and would like the lights to be turned off so they do not distract the occupants during the night.

**Comment by tube0013** [comment]
Unfortunately they are tied into the lan module on the boards and no way to change the behaviors. (They come on even when the esp32 has no fw loaded

Recommend a sharpie or some dark nail polish to paint over them.
