### ISSUE TITLE
Cc2652 coordinator issues 

### ISSUE THREAD

**Issue by jscherry** [tube0013/tube_gateways#7]
Sorry if this is in the wrong area. I have a tubes cc2652 coordinator and the router. Router has been flawless. Coordinator just drops out of hom assistant using zha and I have to power cycle the coordinator to see it again. Also before having these issues I had devices connected as children through the coordinator and now I can’t get a device to connect to it? Any help is greatly appreciated

**Comment by tube0013** [comment]
Can you send me a message at store  at tubeszb.com 

If it isn't working reliably I will swap it out.

**Comment by jscherry** [comment]
I can’t find a email link on the store sight. That’s why I posted on GitHub.

**Comment by tube0013** [comment]
It's store@tubeszb.com

**Comment by jscherry** [comment]
Just emailed you
