### ISSUE TITLE
Flashed router but firmware didn't change in Zigbee2MQTT

### ISSUE THREAD

**Issue by drjjr2** [tube0013/tube_gateways#74]
I am thinking it's something I've done wrong. I have it connected and the cc2538-bsl.py script acts like it completes and verifies, but the version in Zigbee2MQTT still reads "20210128" I have removed and readded the device to the Zigbee network.

I flashed the tubeszb_router_20220223.hex file and also tried CC1352P2_CC2652P_launchpad_router_20220125.hex. Same result.

Any ideas on what to try?

**Comment by drjjr2** [comment]
Following up:
Doing a read of the basic cluster shows the date code of the firmware I flashed:
Read result of 'genBasic': {"swBuildId":"20220125"}

**Comment by tube0013** [comment]
It's in the sw_build_id attribute

![image](https://user-images.githubusercontent.com/11084412/178605998-339458df-e4ab-454c-8cd3-3d2a7616b48a.jpeg)

**Comment by drjjr2** [comment]
Well, patience is a virtue. Just needed to wait some amount of time. Just checked and it's 20220125 in the firmware version of the device info.

**Comment by tube0013** [comment]
I posted screenshot from one of mine not on latest 😂
