### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by ripvega** [tube0013/tube_gateways#84]
I'm getting the above message when attempting first install.

I installed on another HA instance without issue.

It's the Ethernet USB powered version.

It's connected and is discovered by HA and shows up in ESPHome with all switches available.

What do I need to check?

**Comment by tube0013** [comment]
Debug logging will help to figure out what is actually happening. Also make sure there is nothing else connected to the coordinator's network port.

**Comment by ripvega** [comment]
It seems that it can't be configured when I connect from outside the network.

All is fine now, thank you.
