### ISSUE TITLE
Implement support for new native tcp:// protocol for TCP/IP connection in Home Assistant's ZHA integration?

### ISSUE THREAD

**Issue by Hedda** [tube0013/tube_gateways#87]
puddly and agners have implemented a new zigpy packet API and native tcp:// protocol that the ZHA integration will not be able to use.

Their new tcp:// protocol will allow the ZHA integration and zigpy radio library/libraries to communicate with the radio using TCP/IP which should make for a much faster and more stable connection oven a network in theory.

Could you maybe look into implementing this in your ESPHome builds as an alternative to tunnelling via the ser2net style serial stream server with socket:// protocol (using pyserial)?

This has been implemented in upstream zigpy-znp and bellows radio libraries but does not think it is yet available in ZHA integration(?). 

See puddly's and agners's related work in zigpy:

https://github.com/zigpy/bellows/pull/489

https://github.com/zigpy/zigpy-znp/issues/179

https://github.com/zigpy/zigpy-znp/pull/171

https://github.com/zigpy/zigpy-deconz/pull/206

https://github.com/zigpy/zigpy/pull/1043

**Comment by tube0013** [comment]
The esp32 doesn't use pyserial this is applicable only to the host system.
