### ISSUE TITLE
How many amps does the router draw?

### ISSUE THREAD

**Issue by nareddyt** [tube0013/tube_gateways#88]
Documentation at https://www.tubeszb.com/product/cc_router/4 only mentions the following:

> Mains Powered via Micro USB cable and 5v power supply (Not Included)

How many amps should the power supply provide? I currently have a bunch of 5V 1A USB wall outlets that power my ESP32s, I hope I can repurpose them for the routers. Is 1A enough power?

**Comment by tube0013** [comment]
I will update docs but 1 amp is more than sufficient
